HEALTHCARE_ROLE_PROFILES = {
    "registered_nurse": {
        "label": "Registered Nurse (RN)",
        "company": "Generic Healthcare Provider",
        "job_family": "Nursing / Clinical Care",
        "min_education": "associate or bachelor nursing degree",
        "must_have_signals": [
            "rn_license",
            "clinical_experience",
        ],
        "preferred_signals": [
            "bls_acls",
            "hospital_experience",
            "patient_care",
            "emr_systems",
            "hipaa_compliance",
            "communication",
            "teamwork",
        ],
        "weights": {
            "rn_license": 5,
            "clinical_experience": 5,
            "bls_acls": 3,
            "hospital_experience": 3,
            "patient_care": 4,
            "emr_systems": 2,
            "hipaa_compliance": 2,
            "communication": 2,
            "teamwork": 1,
            "education": 2,
        },
        "interview_threshold": 20,
        "hold_threshold": 13,
        "assessment_required": True,
        "assessment_types": [
            "clinical judgment",
            "patient-care scenario",
            "compliance awareness",
        ],
        "target_outcomes": [
            "safe patient care",
            "clinical decision support",
            "documentation accuracy",
            "care-team collaboration",
            "HIPAA-aware workflow",
        ],
    },

    "medical_assistant": {
        "label": "Medical Assistant",
        "company": "Generic Healthcare Provider",
        "job_family": "Clinical Support",
        "min_education": "high school or medical assistant certificate",
        "must_have_signals": [
            "patient_care",
            "communication",
        ],
        "preferred_signals": [
            "clinical_experience",
            "emr_systems",
            "hipaa_compliance",
            "teamwork",
            "bls_acls",
        ],
        "weights": {
            "rn_license": 0,
            "clinical_experience": 3,
            "bls_acls": 2,
            "hospital_experience": 1,
            "patient_care": 5,
            "emr_systems": 3,
            "hipaa_compliance": 3,
            "communication": 4,
            "teamwork": 2,
            "education": 2,
        },
        "interview_threshold": 17,
        "hold_threshold": 11,
        "assessment_required": True,
        "assessment_types": [
            "patient interaction",
            "clinical support workflow",
            "compliance awareness",
        ],
        "target_outcomes": [
            "patient intake support",
            "accurate charting",
            "clinical team coordination",
            "patient communication",
        ],
    },

    "clinical_research_coordinator": {
        "label": "Clinical Research Coordinator",
        "company": "Generic Healthcare / Research Organization",
        "job_family": "Clinical Research",
        "min_education": "bachelor preferred",
        "must_have_signals": [
            "clinical_experience",
            "hipaa_compliance",
            "communication",
        ],
        "preferred_signals": [
            "patient_care",
            "emr_systems",
            "teamwork",
            "education",
        ],
        "weights": {
            "rn_license": 1,
            "clinical_experience": 4,
            "bls_acls": 1,
            "hospital_experience": 2,
            "patient_care": 3,
            "emr_systems": 3,
            "hipaa_compliance": 4,
            "communication": 4,
            "teamwork": 2,
            "education": 3,
        },
        "interview_threshold": 18,
        "hold_threshold": 12,
        "assessment_required": True,
        "assessment_types": [
            "protocol comprehension",
            "documentation accuracy",
            "compliance awareness",
        ],
        "target_outcomes": [
            "study coordination",
            "patient communication",
            "research documentation",
            "regulatory compliance",
            "cross-functional coordination",
        ],
    },
}
            "relationship development",
        ],
    },
}
