BANK_ROLE_PROFILES = {
    "bofa_relationship_banker": {
        "label": "BoA Relationship Banker",
        "min_education": "high school",
        "must_have_signals": [
            "client_service",
            "communication",
            "relationship_building",
        ],
        "preferred_signals": [
            "banking_experience",
            "cash_handling",
            "digital_banking_education",
            "sales",
            "problem_solving",
            "operations",
        ],
        "weights": {
            "client_service": 4,
            "communication": 3,
            "relationship_building": 4,
            "sales": 3,
            "banking_experience": 4,
            "cash_handling": 2,
            "digital_banking_education": 3,
            "operations": 2,
            "problem_solving": 2,
            "adaptability": 1,
            "education": 2,
        },
        "interview_threshold": 19,
        "hold_threshold": 13,
    },
    "chase_associate_banker": {
        "label": "Chase Associate Banker",
        "min_education": "high school",
        "must_have_signals": [
            "client_service",
            "communication",
            "relationship_building",
        ],
        "preferred_signals": [
            "cash_handling",
            "digital_banking_education",
            "operations",
            "problem_solving",
            "banking_experience",
        ],
        "weights": {
            "client_service": 4,
            "communication": 3,
            "relationship_building": 4,
            "sales": 2,
            "banking_experience": 3,
            "cash_handling": 3,
            "digital_banking_education": 4,
            "operations": 3,
            "problem_solving": 2,
            "adaptability": 1,
            "education": 2,
        },
        "interview_threshold": 18,
        "hold_threshold": 12,
    },
    "generic_retail_banker": {
        "label": "Generic Retail Banker",
        "min_education": "high school",
        "must_have_signals": [
            "client_service",
            "communication",
        ],
        "preferred_signals": [
            "relationship_building",
            "cash_handling",
            "banking_experience",
            "digital_banking_education",
            "sales",
            "operations",
        ],
        "weights": {
            "client_service": 4,
            "communication": 3,
            "relationship_building": 3,
            "sales": 2,
            "banking_experience": 3,
            "cash_handling": 3,
            "digital_banking_education": 3,
            "operations": 2,
            "problem_solving": 2,
            "adaptability": 1,
            "education": 2,
        },
        "interview_threshold": 17,
        "hold_threshold": 11,
    },
}
